version: 0.0
os: linux
files:
   - source: /
     destination: /var/www
hooks:
   ApplicationStop:
    - location: scripts/application-stop.sh
      runas: root
      timeout: 120
   BeforeInstall:
    - location: scripts/before-install.sh
      runas: root
      timeout: 120
   AfterInstall:
    - location: scripts/after-install.sh
      runas: root
      timeout: 240
   ApplicationStart:
    - location: scripts/application-start.sh
      runas: root
      timeout: 120
   ValidateService:
    - location: scripts/validate-service.sh
      runas: root
      timeout: 120
